# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: paloaltonetworks/cov
        # You may pin to the exact commit or the version.
        # uses: PaloAltoNetworks/cov@d48812e1c0a3f4f056c104411b410b2957c51f91
        uses: PaloAltoNetworks/cov@3.2.1
        with:
          # The main branch name.
          main_branch: main # default is main
          # Running mode. Either 'coverage', 'send-status' or 'both'.
          cov_mode: coverage # default is coverage
          # The name of the coverage file to use.
          cov_file: coverage.out # default is coverage.out
          # Default required coverage percentage.
          cov_threshold: 95 # optional, default is 90
          # The version to use for cov.
          cov_version: ${{github.action_ref}} # default is ${{github.action_ref}}
          # In mode 'send-status', pass the workflow id that generated the cov report.
                
